export const FETCH_ADDONS = 'projects/FETCH_ADDONS';
export const FETCH_PROJECTS = 'projects/FETCH_PROJECTS';

export const FETCH_PROJECT = 'projects/FETCH_PROJECT';
export const FETCH_PROJECT_WITH_IMAGE = 'FETCH_PROJECT_WITH_IMAGE';
export const CHECK_PROJECT_EXISTENCE = 'projects/CHECK_PROJECT_EXISTENCE';
export const CHECK_PROJECT_EXISTENCE_UPDATE = 'projects/CHECK_PROJECT_EXISTENCE_UPDATE';

export const CREATE_PROJECT = 'projects/CREATE_PROJECT';
export const EDIT_PROJECT = 'projects/SAVE_PROJECT';

export const DELETE_PROJECT = 'projects/DELETE_PROJECT';

export const GENERATE_PRESENTATION = 'GENERATE_PRESENTATION';
export const GENERATE_PRESENTATION_SINGLE = 'GENERATE_PRESENTATION_SINGLE';

export const REMOVE_PROJECT_IMAGE = 'projects/REMOVE_PROJECT_IMAGE';
export const UPDATE_PROJECT_IMAGE = 'projects/UPDATE_PROJECT_IMAGE';
