export const FETCH_ADDONS = 'projects/FETCH_ADDONS';
export const FETCH_PROJECTS = 'projects/FETCH_PROJECTS';

export const FETCH_PROJECT = 'projects/FETCH_PROJECT';
export const FETCH_PROJECT_WITH_IMAGE = 'FETCH_PROJECT_WITH_IMAGE';

export const DELETE_PROJECT = 'projects/DELETE_PROJECT';

export const GENERATE_PRESENTATION = 'GENERATE_PRESENTATION';
export const GENERATE_PRESENTATION_SINGLE = 'GENERATE_PRESENTATION_SINGLE';

export const SYNC_PARAMS = 'SYNC_PARAMS';
export const RESET_FILTERS_TECHNOLOGIES = 'RESET_FILTERS_TECHNOLOGIES';
